title: "Xuanyu's Academic Website"
description: "Research and Experience"
theme: jekyll-theme-minimal # Choose any Jekyll theme, like jekyll-theme-cayman
url: "https://github.com/Xuanyuuuu/experiences" # Replace with your GitHub Pages URL
baseurl: "" # Leave this blank for GitHub Pages
